def index_monster(self, monsterList):
    for i in monster:
        if i = 0:
            name = monster[i]
        elif i = 1:
            xp = monster[i]
        elif i = 2:
            ranged = monster[i]
        elif i = 3:
            melee = monster[i]
        elif i = 4:
            strength = monster[i]
        elif i = 5:
            dexterity = monster[i]
        elif i = 6:
            constitution = monster[i]
        elif i = 7:
            intelligence = monster[i]
        elif i = 8:
            wisdom = monster[i]
        elif i = 9:
            charisma = monster[i]
        elif i = 10:
            size = monster[i]
        elif i = 11:
            CMB = monster[i]
        elif i = 12:
            CMD = monster[i]
        elif i = 13:
            AC = monster[i]
        elif i = 14:
            fortitude = monster[i]
        elif i = 15:
            reflex = monster[i]
        elif i = 16:
            will = monster[i]
        elif i = 17:
            speed = monster[i]
        elif i = 18:
            hp = monster[i]
        elif i = 19:
            cr = monster[i]
